services:
  - type: web
    name: PIL-Dashboard
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: gunicorn app:app
    envVars:
      - key: SQLALCHEMY_DATABASE_URI
        value: mysql+mysqlconnector://if0_36912685:rohitkosqu@rohitappdb.42web.io:3306/if0_36912685_Dashboard
      - key: SECRET_KEY
        value: PIL-Kosqu
      - key: MAIL_SERVER
        value: smtp.example.com
      - key: MAIL_PORT
        value: "587"
      - key: MAIL_USE_TLS
        value: "True"
      - key: MAIL_USERNAME
        value: your_email@example.com
      - key: MAIL_PASSWORD
        value: your_email_password
